workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: 3.29.1
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Flutter pub get
        script: flutter packages pub get
      - name: Pod install
        script: |
          cd ios && pod install --repo-update
      - name: Build iOS Release
        script: |
          flutter build ipa \
            --release \
            --no-tree-shake-icons \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mchdtdagvrn@gmail.com
        notify:
          success: true
          failure: true
